[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dial-sft"
version = "0.1.0"
description = "Dialog SFT with MLM training"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "AvgJoe-cpu"},
]
dependencies = [
    "transformers",
    "datasets==3.4.0",
    "hydra-core>=1.3",
    "trl",
    "jinja2",
    "torchmetrics",
    "torch",
    "tensorboardX",
    "tensorboard",
    "typer[all]",

]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "flake8",
]


[tool.pylint.format]
max-line-length = 88
[tool.black]
line-length = 88
[tool.isort]
profile = "black"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]